/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.CalcularIF;
import control.Ejercicios;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Calcular;
import model.ejercicio2;

/**
 *
 * @author david.gomeza
 */
public class CalculadoraPlus extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraPlus
     *
     *
     */
    public int Operator, Valor;
    public String valor1, valor2;

    private final CalcularIF control = new Calcular();
    private Ejercicios control2;

    public CalculadoraPlus() {
        initComponents();
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jFrame1 = new javax.swing.JFrame();
        Navegador = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        Numero2 = new javax.swing.JTextField();
        Numero1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        ComBoxOperador = new javax.swing.JComboBox<>();
        resultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ComBoxBool = new javax.swing.JComboBox<>();
        VauleBol1 = new javax.swing.JTextField();
        VauleBol2 = new javax.swing.JTextField();
        OperatorNum1 = new javax.swing.JComboBox<>();
        VauleBol3 = new javax.swing.JTextField();
        OperatorNum2 = new javax.swing.JComboBox<>();
        VauleBol4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        btnEnviarEjer1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtN1 = new javax.swing.JTextField();
        btnEnviarEjer2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NEmpleados = new javax.swing.JTextField();
        btnEnviarEjer3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Money = new javax.swing.JTextField();
        btnEnviarEjer4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(135, 168, 208));

        Navegador.setBackground(new java.awt.Color(135, 168, 208));
        Navegador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel8.setBackground(new java.awt.Color(222, 236, 252));

        jButton5.setBackground(new java.awt.Color(195, 180, 210));
        jButton5.setText("Calcular");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ComBoxOperador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chose operator", "+ (suma aritmetica)", "- (resta aritmetica)", "* (multiplicacion)", "/ (division)", "% (residuo)", "<< (dezplazar bit izquierda)", ">> (desplazar bit derecha incl signo)", ">>> (desplazar bit derecha  incl cero)", "< (menor que)", "<= (menor o igual que)", "> (mayor que)", ">= (mayor o igual que)", "== (igual) (primitivo)", "!= (desigual) (primitivo)", "& (cambio de bits AND-producto booleano)", "^ (cambio de bits XOR-suma exclusiva booleana)", "| (cambio de bits OR-suma booleana)", "+= (asignacion con operacion)", "-= (asignacion con operacion)", "*=  (asignacion con operacion)", "/=  (asignacion con operacion)", "%=  (asignacion con operacion)", "<<=  (asignacion con operacion)", ">>=  (asignacion con operacion)", ">>>=  (asignacion con operacion)", "&=  (asignacion con operacion)", "^=  (asignacion con operacion)", "|=  (asignacion con operacion)", "= (asignacion)", "++ (incremento unario)", "-- (decremento unario)", "~ (cambio bits)", "+ (suma unaria)", "- (resta unaria)" }));
        ComBoxOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBoxOperadorActionPerformed(evt);
            }
        });

        resultado.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Numero1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ComBoxOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Numero2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComBoxOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        Navegador.addTab("Operadores Num y Log", jPanel8);

        jPanel2.setBackground(new java.awt.Color(222, 236, 252));

        ComBoxBool.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Operator...", "&& (AND condicional)", "|| (OR condicional)", "? (operador ternario)" }));
        ComBoxBool.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComBoxBoolItemStateChanged(evt);
            }
        });

        OperatorNum1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        OperatorNum1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==", "!=", "<", "<=", "> ", ">=" }));

        OperatorNum2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        OperatorNum2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==", "!=", "<", "<=", "> ", ">=" }));

        jButton1.setBackground(new java.awt.Color(195, 180, 210));
        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(VauleBol1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OperatorNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VauleBol2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComBoxBool, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VauleBol3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OperatorNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VauleBol4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VauleBol1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OperatorNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VauleBol2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComBoxBool, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VauleBol3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VauleBol4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OperatorNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        ComBoxBool.getAccessibleContext().setAccessibleParent(jPanel2);

        Navegador.addTab("Condicionales", jPanel2);

        jPanel1.setBackground(new java.awt.Color(222, 236, 252));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Ingresa el numero: ");

        btnEnviarEjer1.setBackground(new java.awt.Color(195, 180, 210));
        btnEnviarEjer1.setText("Enviar");
        btnEnviarEjer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEjer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnviarEjer1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEnviarEjer1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Navegador.addTab("Calcular Cuadrado", jPanel1);

        jPanel3.setBackground(new java.awt.Color(222, 236, 252));

        btnEnviarEjer2.setBackground(new java.awt.Color(195, 180, 210));
        btnEnviarEjer2.setText("Calcular");
        btnEnviarEjer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEjer2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Ingresa el numero: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEnviarEjer2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addComponent(txtN1)))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviarEjer2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        Navegador.addTab("Calcular Cubo", jPanel3);

        jPanel4.setBackground(new java.awt.Color(222, 236, 252));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Ingrese el numero de empleados");

        btnEnviarEjer3.setBackground(new java.awt.Color(195, 180, 210));
        btnEnviarEjer3.setText("Calcular");
        btnEnviarEjer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEjer3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarEjer3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviarEjer3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Navegador.addTab("Calcular Sueldo", jPanel4);

        jPanel5.setBackground(new java.awt.Color(222, 236, 252));

        btnEnviarEjer4.setBackground(new java.awt.Color(195, 180, 210));
        btnEnviarEjer4.setText("Calcular");
        btnEnviarEjer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEjer4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Ingresa el numero: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnviarEjer4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnEnviarEjer4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Navegador.addTab("Calcular Billetes", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Navegador)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navegador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Navegador.getAccessibleContext().setAccessibleName("Logicos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            valor1 = Numero1.getText();
            valor2 = Numero2.getText();
            Operator = ComBoxOperador.getSelectedIndex();

            switch (Operator) {
                case 1 -> // + (suma aritmetica)
                    imprimirResult(control.Add(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 2 -> // - (resta aritmetica)
                    imprimirResult(control.Substract(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 3 -> // * (multiplicacion)
                    imprimirResult(control.Multiply(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 4 -> {
                    // / (division)
                    if (Float.parseFloat(valor2) == 0.0) {
                        error(1);
                    } else {
                        imprimirResult(control.Divide(Float.parseFloat(valor1), Float.parseFloat(valor2)));
                    }
                }

                case 5 -> {
                    // % (residuo)
                    if (Integer.parseInt(valor2) == 0) {
                        error(1);
                    } else {
                        imprimirResult(control.Residue(Integer.parseInt(valor1), Integer.parseInt(valor2)));
                    }
                }

                case 6 -> // << (dezplazar bit izquierda)
                    imprimirResult(control.DisplaceBitsLeft(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 7 -> // >> (desplazar bit derecha incl signo)
                    imprimirResult(control.DisplaceBitsRightWhSig(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 8 -> // >>> (desplazar bit derecha  incl cero)
                    imprimirResult(control.DisplaceBitsRightWhZero(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 9 -> // < (menor que)
                    imprimirResult(control.MinorThat(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 10 -> // <= (menor o igual que)
                    imprimirResult(control.MinorOrEqualThat(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 11 -> // > (mayor que)
                    imprimirResult(control.BiggerThat(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 12 -> // >= (mayor o igual que)
                    imprimirResult(control.BiggerOrEqualThat(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 13 -> // == (igual) (primitivo)
                    imprimirResult(control.Equals(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 14 -> // != (desigual) (primitivo)
                    imprimirResult(control.DesEquals(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 15 -> // & (cambio de bits AND-producto booleano)
                    imprimirResult(control.ProductAnd(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 16 -> // ^ (cambio de bits XOR-suma exclusiva booleana)
                    imprimirResult(control.AdditionXor(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 17 -> // | (cambio de bits OR-suma booleana)
                    imprimirResult(control.AdditionOr(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 18 -> // += (asignacion con operacion)
                    imprimirResultContinuo(control.Add(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 19 -> // -= (asignacion con operacion)
                    imprimirResultContinuo(control.Substract(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 20 -> // *=  (asignacion con operacion)
                    imprimirResultContinuo(control.Multiply(Float.parseFloat(valor1), Float.parseFloat(valor2)));

                case 21 -> {
                    // /=  (asignacion con operacion)
                    if (Float.parseFloat(valor2) == 0.0) {
                        error(1);
                    } else {
                        imprimirResultContinuo(control.Divide(Float.parseFloat(valor1), Float.parseFloat(valor2)));
                    }
                }

                case 22 -> {
                    // %=  (asignacion con operacion)
                    if (Integer.parseInt(valor2) == 0) {
                        error(1);
                    } else {
                        imprimirResultContinuo(control.Residue(Integer.parseInt(valor1), Integer.parseInt(valor2)));
                    }
                }

                case 23 -> // <<=  (asignacion con operacion)
                    imprimirResultContinuo(control.DisplaceBitsLeft(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 24 -> // >>=  (asignacion con operacion)
                    imprimirResultContinuo(control.DisplaceBitsRightWhSig(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 25 -> // >>>=  (asignacion con operacion)
                    imprimirResultContinuo(control.DisplaceBitsRightWhZero(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 26 -> // &=  (asignacion con operacion)
                    imprimirResultContinuo(control.ProductAnd(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 27 -> // ^=  (asignacion con operacion)
                    imprimirResultContinuo(control.AdditionXor(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 28 -> // |=  (asignacion con operacion)
                    imprimirResultContinuo(control.AdditionOr(Integer.parseInt(valor1), Integer.parseInt(valor2)));

                case 29 -> // = (asignacion)
                    Numero1.setText(Numero2.getText());

                case 30 -> // ++  (incremeno unitario)
                    imprimirResultContinuo(control.IncrementUnit(Integer.parseInt(valor1)));

                case 31 ->// --  (Decremento unitario)
                    imprimirResultContinuo(control.DecrementUnit(Integer.parseInt(valor1)));

                case 32 ->// ~  (Cambio de bits)
                    imprimirResult(control.ChangeOfBits(Integer.parseInt(valor1)));

                case 33 ->// Suma unaria
                    imprimirResult(control.SumeUnary(Float.parseFloat(valor1)));

                case 34 -> //resta unaria    
                    imprimirResult(control.RestUnary(Float.parseFloat(valor1)));

                default ->
                    JOptionPane.showMessageDialog(null, "Elige una operación.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lo que escribió no son números", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay errores, revise sus números", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Operator = ComBoxBool.getSelectedIndex();
        try {
            switch (Operator) {
                case 1 -> {
                    // && (AND condicional)
                    if (compararValoresF(OperatorNum1.getSelectedIndex(), VauleBol1.getText(), VauleBol2.getText())
                            && compararValoresF(OperatorNum2.getSelectedIndex(), VauleBol3.getText(), VauleBol4.getText())) {
                        mostrarResult(true);
                    } else {
                        mostrarResult(false);
                    }
                }

                case 2 -> {
                    // || (OR condicional)
                    if (compararValoresF(OperatorNum1.getSelectedIndex(), VauleBol1.getText(), VauleBol2.getText())
                            || compararValoresF(OperatorNum2.getSelectedIndex(), VauleBol3.getText(), VauleBol4.getText())) {
                        mostrarResult(true);
                    } else {
                        mostrarResult(false);
                    }
                }

                case 3 -> {
                    // ? : (operador ternario)
                    if ((VauleBol3.getText().isEmpty()) || (VauleBol4.getText().isEmpty())) {
                        error(2);
                    } else {
                        if (compararValoresF(OperatorNum1.getSelectedIndex(), VauleBol1.getText(), VauleBol2.getText())) {
                            jLabel1.setText(VauleBol3.getText());
                        } else {
                            jLabel1.setText(VauleBol4.getText());
                        }
                    }
                }

                default ->
                    JOptionPane.showMessageDialog(null, "Elige una operación.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lo que escribió no son números", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay errores, revise sus números", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComBoxBoolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComBoxBoolItemStateChanged

        if (ComBoxBool.getSelectedIndex() == 3) {
            if (OperatorNum2.getItemCount() <= 6) {
                OperatorNum2.setEnabled(false);
                OperatorNum2.addItem("  :");
                OperatorNum2.setSelectedIndex(6);
            }
        } else {
            if (OperatorNum2.getItemCount() > 6) {
                OperatorNum2.setEnabled(true);
                OperatorNum2.removeItem(OperatorNum2.getSelectedItem());
            }
        }
    }//GEN-LAST:event_ComBoxBoolItemStateChanged

    private void btnEnviarEjer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEjer1ActionPerformed
        // TODO add your handling code here:
        try {
            Valor = Integer.parseInt(txtN.getText());
            control2 = new ejercicio2();
            if (Valor < 1) {
                error(3);
            } else {
                imprimirResult(control2.calculateSquare(Valor));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lo que escribió no son números", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay errores, revise sus números", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarEjer1ActionPerformed

    private void btnEnviarEjer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEjer2ActionPerformed
        try {
            Valor = Integer.parseInt(txtN1.getText());
            control2 = new ejercicio2();
            if (Valor < 1) {
                error(3);
            } else {
                imprimirResult(control2.calculateCube(Valor));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lo que escribió no son números", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay errores, revise sus números", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarEjer2ActionPerformed

    private void btnEnviarEjer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEjer3ActionPerformed
        try {
            Valor = Integer.parseInt(NEmpleados.getText());
            control2 = new ejercicio2();

            if (Valor < 1) {
                error(3);
            } else {
                ArrayList<String> Nombres = new ArrayList<>();
                ArrayList<Integer> Horas = new ArrayList<>();
                ArrayList<Double> PrecioHora = new ArrayList<>();
                for (int i = 0; i < Valor; i++) {
                    String entrada = JOptionPane.showInputDialog("Introduce del Trabajador #" + (i + 1) + " El Identificador, las horas trabajadas \n y el sueldo por hora separados por comas (,)");
                    String[] partes = entrada.split(","); // divide la entrada por la coma
                    Nombres.add(partes[0]); // convierte la primera parte a int
                    Horas.add(Integer.valueOf(partes[1]));
                    PrecioHora.add(Double.valueOf(partes[2]));
                }
                imprimirResult(control2.OrganizeSalary(Nombres, control2.calculateSalary(Horas, PrecioHora, Valor), Valor));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lo que escribió no son números", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Hay errores, revise sus números", "Error", JOptionPane.ERROR_MESSAGE);
        }// imprimirResult( control.OrganizeSalary(Nombres, control.calculateSalary(Horas, PrecioHora, n), n));
    }//GEN-LAST:event_btnEnviarEjer3ActionPerformed

    private void btnEnviarEjer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEjer4ActionPerformed
        // TODO add your handling code here:
        try {
            Valor = Integer.parseInt(Money.getText());
            control2 = new ejercicio2();

            if (Valor < 1) {
                error(3);
            } else {
                imprimirResult(control2.CalculateMoney(Valor));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lo que escribió no son números", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Hay errores, revise sus números", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarEjer4ActionPerformed

    private void ComBoxOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBoxOperadorActionPerformed
        if (ComBoxOperador.getSelectedIndex() >= 30) {
            Numero2.setEnabled(false);
            Numero2.setEditable(false);
        }
        else{
            Numero2.setEnabled(true);
            Numero2.setEditable(true);
        }
    }//GEN-LAST:event_ComBoxOperadorActionPerformed

    private void error(int tipoError) {
        switch (tipoError) {
            case 1 -> // Error al dividir por cero
                JOptionPane.showMessageDialog(null, "No divida por cero", "Error", JOptionPane.ERROR_MESSAGE);
            case 2 -> // Error al no ingresar valores
                JOptionPane.showMessageDialog(null, "Hay casillas vacias", "Error", JOptionPane.ERROR_MESSAGE);
            case 3 -> // Solo valores positivos
                JOptionPane.showMessageDialog(null, "Solo numeros positivos", "Error", JOptionPane.ERROR_MESSAGE);
            default ->
                throw new AssertionError();
        }
    }

    // metodos para la primera pestaña
    //-------------------------------------------------------------------
    private void limpiarText() {
        Numero1.setText("");
        Numero2.setText("");
    }

    private void imprimirResult(float valor) {
        resultado.setText("Result: " + valor);
        limpiarText();
    }

    private void imprimirResult(int valor) {
        resultado.setText("Result: " + valor);
        limpiarText();
    }

    private void imprimirResult(boolean valor) {
        resultado.setText("Result: " + valor);
        limpiarText();
    }

    private void imprimirResult(String valor) {
        JOptionPane.showMessageDialog(this, valor);
    }

    private void imprimirResultContinuo(float valor) {
        resultado.setText("Result: " + valor);
        Numero1.setText(String.valueOf(valor));
    }

    private void imprimirResultContinuo(int valor) {
        resultado.setText("Result: " + valor);
        Numero1.setText(String.valueOf(valor));
    }
    //-------------------------------------------------------------------

    // metodos para la segunda pestaña
    //-------------------------------------------------------------------
    private boolean compararValoresF(int operador, String valor1, String valor2) {
        boolean valorBooleano = false;
        switch (operador) {
            case 0 -> // ==
                valorBooleano = control.Equals(Float.parseFloat(valor1), Float.parseFloat(valor2));
            case 1 -> // !=
                valorBooleano = control.DesEquals(Float.parseFloat(valor1), Float.parseFloat(valor2));
            case 2 -> // <
                valorBooleano = control.MinorThat(Float.parseFloat(valor1), Float.parseFloat(valor2));
            case 3 -> // <=
                valorBooleano = control.MinorOrEqualThat(Float.parseFloat(valor1), Float.parseFloat(valor2));
            case 4 -> // >
                valorBooleano = control.BiggerThat(Float.parseFloat(valor1), Float.parseFloat(valor2));
            case 5 -> // >=
                valorBooleano = control.BiggerOrEqualThat(Float.parseFloat(valor1), Float.parseFloat(valor2));
            default ->
                JOptionPane.showMessageDialog(null, "Elige una operación.");
        }
        return valorBooleano;
    }

    private void mostrarResult(boolean v) {
        jLabel1.setText("" + v);
    }
    //-------------------------------------------------------------------

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraPlus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComBoxBool;
    private javax.swing.JComboBox<String> ComBoxOperador;
    private javax.swing.JTextField Money;
    private javax.swing.JTextField NEmpleados;
    private javax.swing.JTabbedPane Navegador;
    private javax.swing.JTextField Numero1;
    private javax.swing.JTextField Numero2;
    private javax.swing.JComboBox<String> OperatorNum1;
    private javax.swing.JComboBox<String> OperatorNum2;
    private javax.swing.JTextField VauleBol1;
    private javax.swing.JTextField VauleBol2;
    private javax.swing.JTextField VauleBol3;
    private javax.swing.JTextField VauleBol4;
    private javax.swing.JButton btnEnviarEjer1;
    private javax.swing.JButton btnEnviarEjer2;
    private javax.swing.JButton btnEnviarEjer3;
    private javax.swing.JButton btnEnviarEjer4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtN1;
    // End of variables declaration//GEN-END:variables

    private void setLocationReIativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
